'use server';
import { redirect } from 'next/navigation';import { revalidatePath } from 'next/cache';import { db } from '@/lib/db';import { requireAdmin, requireUser } from '@/lib/auth';import { builderSchema, inspectionSchema, templateSchema } from '@/lib/validations';import { missingRequired } from '@/lib/inspection-utils';
export type CreateInspectionState={ok:boolean;message?:string;values?:Record<string,string>;fieldErrors?:Record<string,string>};
function formValues(fd:FormData){return Object.fromEntries(Array.from(fd.entries()).map(([key,value])=>[key,typeof value==='string'?value:''])) as Record<string,string>}
function firstFieldErrors(error:unknown){if(!error||typeof error!=='object'||!('flatten' in error)||typeof (error as any).flatten!=='function')return {};const flattened=(error as any).flatten();return Object.fromEntries(Object.entries(flattened.fieldErrors as Record<string,string[]>).map(([key,messages])=>[key,messages[0]]).filter(([,message])=>Boolean(message))) as Record<string,string>}
export async function createTemplate(fd:FormData){const u=await requireAdmin();const data=templateSchema.parse(Object.fromEntries(fd));const t=await db.template.create({data:{...data,createdById:u.id}});await db.auditLog.create({data:{userId:u.id,action:'template created',entityType:'Template',entityId:t.id}});redirect(`/templates/${t.id}/builder`)}
export async function saveTemplate(payload:unknown){const u=await requireAdmin();const p=builderSchema.parse(payload as any);const id=(payload as any).id as string;await db.$transaction(async (tx:any)=>{await tx.template.update({where:{id},data:{name:p.name,description:p.description,buildingType:p.buildingType,category:p.category,isActive:p.isActive}});const sectionIds=p.sections.map(s=>s.id).filter(Boolean) as string[];await tx.templateSection.deleteMany({where:{templateId:id,id:{notIn:sectionIds.length?sectionIds:['__none__']}}});for(const s of p.sections){const section=s.id?await tx.templateSection.update({where:{id:s.id},data:{title:s.title,description:s.description,sortOrder:s.sortOrder}}):await tx.templateSection.create({data:{templateId:id,title:s.title,description:s.description,sortOrder:s.sortOrder}});const itemIds=s.items.map(i=>i.id).filter(Boolean) as string[];await tx.templateItem.deleteMany({where:{sectionId:section.id,id:{notIn:itemIds.length?itemIds:['__none__']}}});for(const it of s.items){const data={sectionId:section.id,title:it.title,instruction:it.instruction,responseType:it.responseType,isRequired:it.isRequired,requiresPhoto:it.requiresPhoto,requiresSeverity:it.requiresSeverity,allowPhoto:it.allowPhoto,optionsJson:it.options,sortOrder:it.sortOrder,isActive:it.isActive};it.id?await tx.templateItem.update({where:{id:it.id},data}):await tx.templateItem.create({data});}}await tx.auditLog.create({data:{userId:u.id,action:'template updated',entityType:'Template',entityId:id}})});revalidatePath('/templates');return {ok:true}}
export async function createInspection(_prevState:CreateInspectionState,fd:FormData):Promise<CreateInspectionState>{const u=await requireUser();const values=formValues(fd);const parsed=inspectionSchema.safeParse(values);if(!parsed.success)return {ok:false,message:'Please fix the highlighted fields before starting the inspection.',values,fieldErrors:firstFieldErrors(parsed.error)};const scheduledDate=new Date(`${parsed.data.scheduledDate}T00:00:00.000Z`);if(Number.isNaN(scheduledDate.getTime()))return {ok:false,message:'Please choose a valid scheduled date.',values,fieldErrors:{scheduledDate:'Choose a valid scheduled date'}};const ins=await db.inspection.create({data:{...parsed.data,inspectorId:u.id,scheduledDate}});await db.auditLog.create({data:{userId:u.id,action:'inspection created',entityType:'Inspection',entityId:ins.id}});redirect(`/inspections/${ins.id}`)}
export async function completeInspection(id:string){const u=await requireUser();const ins=await db.inspection.findUnique({where:{id},include:{template:{include:{sections:{include:{items:true}}}},responses:true}});if(!ins) throw new Error('Inspection not found');const items=ins.template.sections.flatMap(s=>s.items);const missing=missingRequired(items,ins.responses);if(missing.length) return {ok:false,missing:missing.map(m=>m.title)};await db.inspection.update({where:{id},data:{status:'COMPLETED',completedAt:new Date()}});await db.auditLog.create({data:{userId:u.id,action:'inspection completed',entityType:'Inspection',entityId:id}});revalidatePath(`/inspections/${id}`);return {ok:true,missing:[]}}
